language: csharp
solution: evReact.sln
env:
 - CFG=Debug
 - CFG=Release
script:
 - xbuild /p:Configuration=$CFG evReact.sln
 - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./test/bin/$CFG/net40/test.dll
